plugins:
  - jekyll-theme-hamilton
title: OptimistiCompound's homepage

description: Bookmark this to keep an eye on my project updates!
author: Yong Zhong
# avatar: /logo.png
email: yzhong1024@gmail.com

# paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# # =========================
# twitter:
#   username: ngzhio
#   card: summary
# logo: logo.png
social:
  name: Yong Zhong
  # links:
  #   - https://twitter.com/ngzhio
  #   - https://www.facebook.com/ngzhio
    - https://github.com/Optimisticompound
# google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
